# Generated by Django 3.2.25 on 2026-09-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appArticle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleconfig',
            options={'ordering': ['-modified'], 'verbose_name': 'Artikel/Seite', 'verbose_name_plural': '01. Artikel/Seiten'},
        ),
        migrations.AlterModelOptions(
            name='articlesection',
            options={'ordering': ['order'], 'verbose_name': 'Abschnitt/Segment', 'verbose_name_plural': '02. Abschnitte/Segmente'},
        ),
        migrations.AlterModelOptions(
            name='groupitem',
            options={'ordering': ['order'], 'verbose_name': 'Dienst-/Item', 'verbose_name_plural': '04. Dienste/Items'},
        ),
        migrations.AlterModelOptions(
            name='itemlink',
            options={'ordering': ['order'], 'verbose_name': 'Link', 'verbose_name_plural': '05. Links'},
        ),
        migrations.AlterModelOptions(
            name='sectiongroup',
            options={'ordering': ['order'], 'verbose_name': 'Dienst-/Item-Gruppe', 'verbose_name_plural': '03. Dienst-/Item-Gruppen'},
        ),
    ]
