# Generated by Django 2.1.3 on 2020-08-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useroperations', '0002_inspiredownloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSliderElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('anchor_href', models.URLField(max_length=255)),
                ('image_src', models.URLField(max_length=255)),
            ],
        ),
    ]
