# Generated by Django 2.2.17 on 2021-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useroperations', '0003_applicationsliderelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(default=False)),
                ('dispatch_type', models.CharField(choices=[('information', 'Information')], max_length=20)),
            ],
        ),
    ]
