# Generated by Django 3.2.11 on 2023-06-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useroperations', '0005_applicationsliderelement_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('layer_id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_pos', models.IntegerField()),
                ('layer_parent', models.CharField(max_length=50)),
                ('layer_name', models.CharField(max_length=255)),
                ('layer_title', models.CharField(max_length=255)),
                ('layer_queryable', models.IntegerField()),
                ('layer_minscale', models.IntegerField(blank=True, null=True)),
                ('layer_maxscale', models.IntegerField(blank=True, null=True)),
                ('layer_dataurl', models.CharField(blank=True, max_length=255, null=True)),
                ('layer_metadataurl', models.CharField(blank=True, max_length=255, null=True)),
                ('layer_abstract', models.TextField(blank=True, null=True)),
                ('layer_searchable', models.IntegerField(blank=True, null=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('inspire_download', models.IntegerField(blank=True, null=True)),
                ('export2csw', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'layer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WfsFeaturetype',
            fields=[
                ('featuretype_id', models.AutoField(primary_key=True, serialize=False)),
                ('featuretype_name', models.CharField(max_length=255)),
                ('featuretype_title', models.CharField(blank=True, max_length=200, null=True)),
                ('featuretype_srs', models.CharField(blank=True, max_length=50, null=True)),
                ('featuretype_searchable', models.IntegerField(blank=True, null=True)),
                ('featuretype_abstract', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('featuretype_latlon_bbox', models.CharField(blank=True, max_length=255, null=True)),
                ('inspire_download', models.IntegerField(blank=True, null=True)),
                ('featuretype_schema', models.TextField(blank=True, null=True)),
                ('featuretype_schema_problem', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wfs_featuretype',
                'managed': False,
            },
        ),
    ]
